### ISSUE TITLE
Black Body

### ISSUE THREAD

**Issue by Uru-hara** [lvoxx/LSCherry#15]
![image](https://github.com/user-attachments/assets/b2e3ae2d-b381-462f-bd8d-41d0bb24c76d)

**Comment by lvoxx** [comment]
You can try delete these 3 nodes, this is a feature of blender 4.2 when open 4.0, 4.1 version. Note that LSCherry now only render at EEVEE, Cycles is not supported yet.
* Next time, pls censor sensitive screenshot *
![ảnh](https://github.com/user-attachments/assets/0c391c1f-b6a1-4993-b47c-3900c62ca5c8)
